import logging
from datetime import datetime
from typing import List, Optional

from fastapi import Depends, HTTPException
from pydantic import ConfigDict, BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from core.database import get_db
from models.wallets import Wallets
from models.wallet_transactions import Wallet_transactions
from routers.base_router import create_crud_router
from services.disbursements import DisbursementsService
from dependencies.auth import get_current_user
from schemas.auth import UserResponse

logger = logging.getLogger(__name__)


# ---------- Pydantic Schemas ----------
class DisbursementsData(BaseModel):
    """Entity data schema (for create/update)"""
    external_id: str = None
    xendit_id: str = None
    amount: float
    currency: str = None
    bank_code: str = None
    account_number: str = None
    account_name: str = None
    description: str = None
    status: str = None
    disbursement_type: str = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class DisbursementsUpdateData(BaseModel):
    """Update entity data (partial updates allowed)"""
    external_id: Optional[str] = None
    xendit_id: Optional[str] = None
    amount: Optional[float] = None
    currency: Optional[str] = None
    bank_code: Optional[str] = None
    account_number: Optional[str] = None
    account_name: Optional[str] = None
    description: Optional[str] = None
    status: Optional[str] = None
    disbursement_type: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class DisbursementsResponse(BaseModel):
    """Entity response schema"""
    id: int
    user_id: str
    external_id: Optional[str] = None
    xendit_id: Optional[str] = None
    amount: float
    currency: Optional[str] = None
    bank_code: Optional[str] = None
    account_number: Optional[str] = None
    account_name: Optional[str] = None
    description: Optional[str] = None
    status: Optional[str] = None
    disbursement_type: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class DisbursementsListResponse(BaseModel):
    """List response schema"""
    items: List[DisbursementsResponse]
    total: int
    skip: int
    limit: int


class DisbursementsBatchCreateRequest(BaseModel):
    """Batch create request"""
    items: List[DisbursementsData]


class DisbursementsBatchUpdateItem(BaseModel):
    """Batch update item"""
    id: int
    updates: DisbursementsUpdateData


class DisbursementsBatchUpdateRequest(BaseModel):
    """Batch update request"""
    items: List[DisbursementsBatchUpdateItem]


class DisbursementsBatchDeleteRequest(BaseModel):
    """Batch delete request"""
    ids: List[int]


# ---------- Helpers ----------
async def _require_php_balance(db: AsyncSession, user_id: str, amount: float) -> Wallets:
    """Check user has sufficient PHP wallet balance. Raises 402 if insufficient."""
    result = await db.execute(
        select(Wallets).where(Wallets.user_id == user_id, Wallets.currency == "PHP")
    )
    wallet = result.scalar_one_or_none()
    balance = float(wallet.balance) if wallet else 0.0
    if balance <= 0:
        raise HTTPException(
            status_code=402,
            detail="Insufficient balance. Your wallet balance is ₱0.00. Please top up to continue.",
        )
    if balance < amount:
        raise HTTPException(
            status_code=402,
            detail=f"Insufficient balance. Available: ₱{balance:,.2f}, Required: ₱{amount:,.2f}. Please top up.",
        )
    return wallet


async def _deduct_php_balance(db: AsyncSession, wallet: Wallets, user_id: str, amount: float, note: str):
    """Deduct amount from PHP wallet and record a wallet transaction."""
    balance_before = wallet.balance
    wallet.balance = round(wallet.balance - amount, 2)
    wallet.updated_at = datetime.now()
    wtxn = Wallet_transactions(
        user_id=user_id,
        wallet_id=wallet.id,
        transaction_type="disbursement",
        amount=-amount,
        balance_before=balance_before,
        balance_after=wallet.balance,
        note=note,
        status="completed",
        created_at=datetime.now(),
    )
    db.add(wtxn)
    await db.commit()


# ---------- Router ----------
# All standard CRUD endpoints are generated by the factory; the create
# endpoint is handled separately to enforce the PHP balance check.
router = create_crud_router(
    prefix="/api/v1/entities/disbursements",
    tags=["disbursements"],
    service_class=DisbursementsService,
    entity_name="Disbursements",
    data_schema=DisbursementsData,
    update_schema=DisbursementsUpdateData,
    response_schema=DisbursementsResponse,
    list_response_schema=DisbursementsListResponse,
    batch_create_schema=DisbursementsBatchCreateRequest,
    batch_update_schema=DisbursementsBatchUpdateRequest,
    batch_delete_schema=DisbursementsBatchDeleteRequest,
    include_create=False,
)


@router.post("", response_model=DisbursementsResponse, status_code=201)
async def create_disbursements(
    data: DisbursementsData,
    current_user: UserResponse = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Create a new disbursements. Requires sufficient PHP wallet balance."""
    logger.debug(f"Creating new disbursements with data: {data}")

    user_id = str(current_user.id)

    # Balance gate — must have enough PHP to cover the disbursement
    wallet = await _require_php_balance(db, user_id, data.amount)

    service = DisbursementsService(db)
    try:
        result = await service.create(data.model_dump(), user_id=user_id)
        if not result:
            raise HTTPException(status_code=400, detail="Failed to create disbursements")

        # Deduct from PHP wallet on successful creation
        await _deduct_php_balance(
            db, wallet, user_id, data.amount,
            f"Disbursement to {data.account_name or data.account_number or 'recipient'}: {data.description or ''}",
        )

        logger.info(f"Disbursements created successfully with id: {result.id}")
        return result
    except HTTPException:
        raise
    except ValueError as e:
        logger.error(f"Validation error creating disbursements: {str(e)}")
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Error creating disbursements: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")
